### ISSUE TITLE
Minor quibbles

### ISSUE THREAD

**Issue by zehawki** [kyoncy/quill-linkify#2]
Thanks for this excellent package. Some minor asks:

1. The package size is quite large (https://bundlephobia.com/package/quill-linkify@0.1.0) for a tiny matching function. Possible to reduce?
2. Possible to provide an option to turn off needless matching, eg I dont want phone matching. So perhaps the options can allow turning off this matching.

on # 2, I'm doing this to match _nothing_, but perhaps you can provide a cleaner way:

```
    const linkifyOptions = {
      phoneNumber: 'a^',
    };
```

**Comment by kyoncy** [comment]
@zehawki 
Thank you for your good request !

> Possible to reduce?

Thanks, I'll try it !

However, similar library [quill-magic-url](https://bundlephobia.com/package/quill-magic-url@4.1.2)'s package size is larger...
Do you have any idea?

> Possible to provide an option to turn off needless matching

This feature was released in `v0.2.0` !
Able to turn off matching.

**References**
- https://github.com/kyoncy/quill-linkify/pull/3
- https://www.npmjs.com/package/quill-linkify/v/0.2.0

**Comment by zehawki** [comment]
I'm afraid I'm not able to get the new options to work. I dont use TS, so usage is as follows:

```
        linkify: {
          mail: true, // Use default regexp
          phoneNumber: false, // Disable text auto link
        },
```

However neither of these options take effect. In other words, it does NOT linkify emails and it DOES linkify phone numbers. So these options are somehow being dropped? Note that my earlier method continues working:

```
        linkify: {
          phoneNumber: 'a^',
        },
```

**Comment by kyoncy** [comment]
I tried the following, but could not reproduce it.

```typescript
const linkifyOption = {
  mail: true,
  url: false,
  phoneNumber: /a^/
};
```

I tried to output `option` and `typeList` to the console.

https://github.com/kyoncy/quill-linkify/blob/034be64235eba2b1a575715fb4c4d4443d071cb4/src/index.ts#L19-L36

```diff
    if (!Object.keys(options).length) {
      typeList.push(new UrlType(true))
      typeList.push(new MailType(true))
      typeList.push(new PhoneNumberType(true))
    } else if (options) {
      options.url && typeList.push(new UrlType(options.url))
      options.mail && typeList.push(new MailType(options.mail))
      options.phoneNumber && typeList.push(new PhoneNumberType(options.phoneNumber))
    }
+   console.log({ options })
+   console.log({ typeList })
```

![image](https://user-images.githubusercontent.com/24786802/139397542-ebb982ec-c01f-4685-9b24-e55e70580157.png)

@zehawki 
If you have any information about `quill` or `quill-delta` versions that might be helpful in the investigation, I would appreciate it.

**Comment by zehawki** [comment]
Oops, this was a problem on my side, possibly with 2 versions of quill-delta. Resolved and working just fine. Thank you!

PS: My apologies for making you needlessly debug.
